### ISSUE TITLE
Error: 'render' is not exported after running `yarn run ngl build`

### ISSUE THREAD

**Issue by milmazz** [garciparedes/ng-katex#178]
After trying to build a component which uses [angular-librarian](https://github.com/gonzofish/angular-librarian) for the Angular 2+ scaffolding setup and uses `ng-katex` as a dependency I receive the following error after running `yarn run ngl build`.

I made a basic component to reproduce the error, you can find the structure here:

https://github.com/milmazz/kat

```
D:\kat [master +19 ~0 -0 !]> yarn run ngl build
yarn run v1.5.1
$ D:\kat\node_modules\.bin\ngl build

> kat@0.1.0 prebuild D:\kat
> rimraf dist out-tsc


> kat@0.1.0 build D:\kat
> node ./tasks/build

Copying `src` files into `build`
> Complete
Inlining resources
> Complete
Compiling code
> Complete
Copying typings + metadata to `dist`
> Complete
Generating bundles via rollup
[Librarian]: > Build failed

{ Error: 'render' is not exported by node_modules\katex\dist\katex.js
    at error (D:\kat\node_modules\rollup\dist\rollup.js:189:14)
    at Module.error (D:\kat\node_modules\rollup\dist\rollup.js:16532:3)
    at Module.trace (D:\kat\node_modules\rollup\dist\rollup.js:16629:10)
    at ModuleScope.findVariable (D:\kat\node_modules\rollup\dist\rollup.js:13971:22)
    at FunctionScope.findVariable (D:\kat\node_modules\rollup\dist\rollup.js:11545:33)
    at Scope.findVariable (D:\kat\node_modules\rollup\dist\rollup.js:11545:33)
    at FunctionScope.findVariable (D:\kat\node_modules\rollup\dist\rollup.js:11545:33)
    at Scope.findVariable (D:\kat\node_modules\rollup\dist\rollup.js:11545:33)
    at Node._bindVariableIfMissing (D:\kat\node_modules\rollup\dist\rollup.js:12628:31)
    at Node.bindNode (D:\kat\node_modules\rollup\dist\rollup.js:12623:8)
  code: 'MISSING_EXPORT',
  url: 'https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module',
  pos: 111,
  loc:
   { file: 'D:\\kat\\node_modules\\ng-katex\\ng-katex.esm.js',
     line: 1,
     column: 111 },
  frame: '1: import{Component,EventEmitter,Input,Output,Injectable,Directive,ElementRef,NgModule}from"@angular/core";import{render}from"katex";function __decorate(e,t,o,n){var r,a=arguments.length,i=a<3?t:null===n?n=Object.getOwnPropertyDescriptor(t,o):n;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)i=Reflect.decorate(e,t,o,n);else for(var p=e.length-1;p>=0;p--)(r=e[p])&&(i=(a<3?r(i):a>3?r(t,o,i):r(t,o))||i);return a>3&&i&&Object.defineProperty(t,o,i),i}function __metadata(e,t){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(e,t)}var KatexComponent=function(){function e(){this.onError=new EventEmitter}return e.prototype.hasError=function(e){this.onError.emit(e)},__decorate([Input(),__metadata("design:type",String)],e.prototype,"equation",void 0),__decorate([Input(),__metadata("design:type",Object)],e.prototype,"options",void 0),__decorate([Output(),__metadata("design:type",Object)],e.prototype,"onError",void 0),e=__decorate([Component({selector:"ng-katex",template:\'\\n    <span [katex]="equation"\\n          [katex-options]="options"\\n          (someEvent)="hasError($event)">\\n    </span>\\n  \'})],e)}(),KatexService=function(){function e(){}return e.prototype.render=function(e,t,o){return render(e,t.nativeElement,o)},e=__decorate([Injectable()],e)}(),KatexDirective=function(){function e(e,t){this.el=e,this.katexService=t,this.onError=new EventEmitter}return e.prototype.ngOnChanges=function(){try{this.katexService.render(this.equation,this.el,this.options)}catch(e){this.onError.emit(e)}},__decorate([Input("katex"),__metadata("design:type",String)],e.prototype,"equation",void 0),__decorate([Input("katex-options"),__metadata("design:type",Object)],e.prototype,"options",void 0),__decorate([Output(),__metadata("design:type",Object)],e.prototype,"onError",void 0),e=__decorate([Directive({selector:"[katex]"}),__metadata("design:paramtypes",[ElementRef,KatexService])],e)}(),KatexModule=function(){function e(){}return e=__decorate([NgModule({imports:[],providers:[KatexService],declarations:[KatexDirective,KatexComponent],exports:[KatexComponent]})],e)}();export{KatexComponent,KatexModule};\n                                                                                                                  ^' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kat@0.1.0 build: `node ./tasks/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kat@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Done in 17.49s.
```

The error message points to this [rollup](https://github.com/rollup/rollup) Troubleshooting guide:

https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

Which states the following:

> Import declarations must have corresponding export declarations in the imported module. For example, if you have `import a from './a.js'` in a module, and a.js doesn't have an `export default` declaration, or `import {foo} from './b.js'`, and b.js doesn't export `foo`, Rollup cannot bundle the code.

But, this seems under the `ng-katex` control, is that right?

How can I fix this error? Any help is greatly appreciated it.

As a side note, everything seems to works fine when I run `yarn run ngl serve`, but I really want to build and pack my library.

**Comment by garciparedes** [comment]
Hi @milmazz ! 

First of all I want to thank you for the bug finding. This weeks I'm being very busy, so I haven't time to solve it. I encourage you to fork this repo and try to solve the `rollup`  compilation bug. 

I need to say you that when I built projects with Angular CLI there wasn't any problem
